// automatically generated by the FlatBuffers compiler, do not modify

package edu.ucsc.soe.srl;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Projection extends Table {
  public static Projection getRootAsProjection(ByteBuffer _bb) { return getRootAsProjection(_bb, new Projection()); }
  public static Projection getRootAsProjection(ByteBuffer _bb, Projection obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Projection __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Range ranges(int j) { return ranges(new Range(), j); }
  public Range ranges(Range obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int rangesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createProjection(FlatBufferBuilder builder,
      int rangesOffset) {
    builder.startObject(1);
    Projection.addRanges(builder, rangesOffset);
    return Projection.endProjection(builder);
  }

  public static void startProjection(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addRanges(FlatBufferBuilder builder, int rangesOffset) { builder.addOffset(0, rangesOffset, 0); }
  public static int createRangesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRangesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endProjection(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishProjectionBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

